### ISSUE TITLE
分辨率不同无法正常运行

### ISSUE THREAD

**Issue by cibimo** [Mufanc/Genshin-SmartFishingRod#1]
本人游戏设置中无1600x900分辨率，
所以需要对不同分辨率进行适配

另外，是否可以检测上钩实现自动收杆？

**Comment by cibimo** [comment]
1680x1050测试成功：

left, right = 625, 1075
position, height = [134], 4

**Comment by cibimo** [comment]
有坑 DPI缩放级别会影响Python中的win32gui.GetWindowRect

**Comment by Mufanc** [comment]
因为急着换鱼竿检测部分就做得比较草率了，目前正在准备 yolov5 目标检测的训练数据，最终目标是实现整个钓点的自动化

**Comment by Mufanc** [comment]
当鱼上钩时动作键图标会发生变化并伴有绿色发光效果，可以基于此做出检测

**Comment by cibimo** [comment]
我尝试了通过rgb值来检测，但经常会识别错误，个人感觉还是得通过识别收杆的图标来实现
（要是能训练出来全自动钓鱼那就厉害了

**Comment by cibimo** [comment]
> 有坑 DPI缩放级别会影响Python中的win32gui.GetWindowRect

```
def get_window_rect(hwnd):
    try:
        f = ctypes.windll.dwmapi.DwmGetWindowAttribute
    except WindowsError:
        f = None
    if f:
        rect = ctypes.wintypes.RECT()
        DWMWA_EXTENDED_FRAME_BOUNDS = 9
        f(ctypes.wintypes.HWND(hwnd),
          ctypes.wintypes.DWORD(DWMWA_EXTENDED_FRAME_BOUNDS),
          ctypes.byref(rect),
          ctypes.sizeof(rect)
          )
        return rect.left, rect.top, rect.right, rect.bottom

left, top, right, bottom = get_window_rect(self.hwnd)
```

**Comment by Mufanc** [comment]
转成HSV并识别色相会比RGB稍好些（但也好不到哪去

**Comment by cibimo** [comment]
> 转成HSV并识别色相会比RGB稍好些（但也好不到哪去

嗯 因为如果去检测某一区域的颜色的话太不可控了，像游戏gui，岸边的岩石，不同水面，不同时间，天空颜色等都可能会导致识别错误

**Comment by cibimo** [comment]
> > 转成HSV并识别色相会比RGB稍好些（但也好不到哪去
> 
> 嗯 因为如果去检测某一区域的颜色的话太不可控了，像游戏gui，岸边的岩石，不同水面，不同时间，天空颜色等都可能会导致识别错误

甚至水下沙滩呈现的颜色也是绿色

**Comment by Mufanc** [comment]
已经亮起的进度条部分为纯色，直接匹配即可，难点在未亮起部分的背景半透明，会受到景物影响；以及钓鱼过程中进度条的颜色变化，可能为金色或红色，均可能影响识别效果
