### ISSUE TITLE
打不开文件  直接闪退

### ISSUE THREAD

**Issue by lNeverl** [Mufanc/Genshin-SmartFishingRod#11]
![image](https://user-images.githubusercontent.com/60817289/136645593-4df6fbb7-3153-462c-be82-3c597c5870ba.png)

**Comment by lNeverl** [comment]
找到问题了 要先退掉游戏在打开文件

**Comment by Mufanc** [comment]
直接在 cmd 通过绝对路径执行 main.exe 会导致“当前目录”下找不到 configs.yml
