### ISSUE TITLE
关于所需要的的第三方模块

### ISSUE THREAD

**Issue by gameovertse** [Mufanc/Genshin-SmartFishingRod#2]
可以麻烦把所需的第三方模块写在一个文件里吗，比如大家常用的requirements.txt这样的。谢谢啦

**Comment by Mufanc** [comment]
这个项目还处于起步阶段，有很多做得不规范的地方，以后会逐步改进的

**Comment by Mufanc** [comment]
感谢反馈，在最新的提交中已添加！
