### ISSUE TITLE
通过”鱼儿上钩啦“提示收杆

### ISSUE THREAD

**Issue by lingkai5wu** [Mufanc/Genshin-SmartFishingRod#3]
钓到鱼时屏幕中上方会出现上钩提示，为不透明纯白色，可以通过提取色值与图片（文字）匹配判断收杆。
从收杆提示出现到钓鱼失败时间较长，可约0.5~1秒判断一次，节约性能。
收杆后可提前点击鼠标，将蓄力位置调整到中间。

**Comment by lingkai5wu** [comment]
另：这次更新识别稳定了很多！！很舒服！

**Comment by Mufanc** [comment]
> 钓到鱼时屏幕中上方会出现上钩提示，为不透明纯白色，可以通过提取色值与图片（文字）匹配判断收杆。
> 从收杆提示出现到钓鱼失败时间较长，可约0.5~1秒判断一次，节约性能。
> 收杆后可提前点击鼠标，将蓄力位置调整到中间。

值得一试！但在不同窗口大小下，文字出现的位置并不相同，需要考虑额外的适配

**Comment by Mufanc** [comment]
已经实现上钩检测啦！上钩时按钮背景会被绿色覆盖，再使用 OpenCV 做模板匹配
![image](https://user-images.githubusercontent.com/47652878/132542119-236c4819-d4a9-4123-ba41-eb17609a88b7.png)
![image](https://user-images.githubusercontent.com/47652878/132542201-88e7538e-b053-4c5e-9907-cb60d962b845.png)
