### ISSUE TITLE
关于脚本检测

### ISSUE THREAD

**Issue by LizzyVZ** [Mufanc/Genshin-SmartFishingRod#5]
可不可以通过修改脚本的识别进程改为识别窗口，然后用云游戏钓鱼，这样就不会被本地检测到了

**Comment by Mufanc** [comment]
理论上只要米哈游不认定使用 Android 模拟器为作弊，套上模拟器再玩就可以基本保证不被检测（还是有可能通过 AI 用户行为识别发现异常的

**Comment by HellSakura** [comment]
云游戏 腾讯start
我这里不能正确识别`PostMessage `指令
不知道其他的平台如何，你可以自己测试下

` manager = Manager('UnityWndClass', '原神')`

**Comment by pinkMint** [comment]
我是参考那个自动弹琴的脚本，那个可以识别腾讯start的窗口

**Comment by pinkMint** [comment]
> 云游戏 腾讯start
> 我这里不能正确识别指令
> 不知道其他的平台如何，你可以自己测试下`PostMessage `
> 
> ` manager = Manager('UnityWndClass', '原神')`



> 云游戏 腾讯start
> 我这里不能正确识别指令
> 不知道其他的平台如何，你可以自己测试下`PostMessage `
> 
> ` manager = Manager('UnityWndClass', '原神')`

**Comment by LizzyVZ** [comment]
就是我是参考自动弹琴的脚本，那个脚本可以识别腾讯云游戏

**Comment by Mufanc** [comment]
云游戏需要在windows中重新定位其宿主的窗口类名和标题，必要时还得做相应的裁剪
