### ISSUE TITLE
背景颜色复杂时产生的bug

### ISSUE THREAD

**Issue by hllshiro** [Mufanc/Genshin-SmartFishingRod#8]
右下鱼钩按钮是半透明图标，在某些色彩较深的位置（例如草地，深色木板）时，识别到右下按钮只有30%左右匹配，会导致脚本无法触发点击。

**Comment by Mufanc** [comment]
感谢反馈，该问题将在下个版本中修复。此外对于当前版本，建议在鱼上钩前将右下角检测区域置于浅蓝色或浅绿色的水面背景上（基本上每个钓点都有），能大幅提升检测成功率
